enum A11y {
    static let banner = "banner"
    static let pairScan = "pair.scan"
    static let pairScanHint = "pair.scan.hint"
    static let pairNearbyEmpty = "pair.nearby.empty"
    static let pairNearbyError = "pair.nearby.error"
    static let pairAddress = "pair.manual.address"
    static let pairCode = "pair.manual.code"
    static let pairSubmit = "pair.manual.submit"
    static let pairDemo = "pair.demo"
    static let pairCodeField = "pair.code.field"
    static let pairCodeSubmit = "pair.code.submit"
    static let pairTrust = "pair.trust"
    static let pairCancel = "pair.cancel"
    static let pairProgress = "pair.progress"
    static let pairError = "pair.error"
    static let missionsLink = "missions.link"
    static let missionsSettings = "missions.settings"
    static let missionsWorkspace = "missions.workspace"
    static let missionsEmpty = "missions.empty"
    static let missionsLeaveDemo = "missions.demo.leave"
    static let tuneField = "tune.field"
    static let tuneSet = "tune.set"
    static let tuneError = "tune.error"
    static let settingsAddServer = "settings.addserver"
    static let settingsName = "settings.name"
    static let settingsSource = "settings.source"
    static let settingsMount = "settings.mount"
    static let settingsOffset = "settings.offset"
    static let settingsAlign = "settings.align"
    static let settingsAlignStatus = "settings.align.status"
    static let settingsHeading = "settings.heading"
    static let settingsUnits = "settings.units"
    static let settingsVoice = "settings.voice"
    static let settingsVoicePick = "settings.voicepick"
    static let settingsVoiceTest = "settings.voicetest"
    static let settingsAccess = "settings.access"
    static let settingsAlways = "settings.always"
    static let settingsPrecise = "settings.precise"
    static let settingsAbout = "settings.about"

    static func pairNearby(_ name: String) -> String { "pair.nearby.\(name)" }
    static func missionRow(_ id: String) -> String { "missions.row.\(id)" }
    static func server(_ id: String) -> String { "settings.server.\(id)" }
}
