[package]
name = "sdrmm-wire"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
probe = []
pin = ["dep:rustls-webpki", "dep:sha2"]

[dependencies]
jiff.workspace = true
serde.workspace = true
serde_json.workspace = true
utoipa.workspace = true
url.workspace = true
thiserror.workspace = true
rustls-webpki = { workspace = true, optional = true, default-features = false, features = ["alloc"] }
sha2 = { workspace = true, optional = true }
