[package]
name = "sdrmm-modem-test-support"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
sdrmm-modem.workspace = true
sdrmm-dsp.workspace = true
sdrmm-test-support.workspace = true
num-complex.workspace = true
serde.workspace = true
serde_json.workspace = true
