[package]
name = "sdrmm-dsp"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
num-complex.workspace = true
rustfft.workspace = true
thiserror.workspace = true

[dev-dependencies]
sdrmm-test-support.workspace = true
criterion.workspace = true

[[bench]]
name = "perf"
harness = false
