[package]
name = "sdrmm-device-soapy"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
sdrmm-wire.workspace = true
sdrmm-device.workspace = true
soapysdr.workspace = true
num-complex.workspace = true
serde_json.workspace = true
tracing.workspace = true
