[package]
name = "sdrmm-engine"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
sdrmm-wire.workspace = true
sdrmm-dsp.workspace = true
sdrmm-device.workspace = true
sdrmm-device-virtual.workspace = true
sdrmm-channels.workspace = true
num-complex.workspace = true
rtrb.workspace = true
arc-swap.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time", "sync"] }
