[package]
name = "sdrmm-cps"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
sdrmm-wire.workspace = true
serialport.workspace = true
serde_json.workspace = true
thiserror.workspace = true
